"""empty message

Revision ID: 3021068f4548
Revises: 76f00395d24b
Create Date: 2020-03-24 08:49:39.315702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3021068f4548"
down_revision = "76f00395d24b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "todo_item", sa.Column("completed", sa.Boolean(), nullable=True)
    )  # set to nullable to be able to update existing rows

    op.execute("UPDATE todo_item SET completed=False WHERE completed IS NULL;")

    op.alter_column("todo_item", "completed", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todo_item", "completed")
    # ### end Alembic commands ###
