"""empty message

Revision ID: d3a442d9247c
Revises: 3021068f4548
Create Date: 2020-04-05 16:47:18.452803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a442d9247c'
down_revision = '3021068f4548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todo_item', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo_item', 'todolist', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_item', type_='foreignkey')
    op.drop_column('todo_item', 'list_id')
    op.drop_table('todolist')
    # ### end Alembic commands ###
